type Anunt {
  title: String!
  imgUrl: String
  categorie: String!
  cantitate: String
  descriere: String
  telefon: String
  email: String
}

type Query {
  allAnunts: [Anunt!]
  anuntsByTitle(title: String!): [Anunt!]
}
